"use client"

import localFont from "next/font/local";
import "../app/styles/layout.css"
import { useRouter } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  const navigateHome = ()=>{
    router.push("/home")
  }

  return (
    <html lang="en">
      <head>
        <title>
          R.R Governance
        </title>
        <link rel="icon" href="/logo.jpg" type="image/x-icon"></link>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
