"use client"

import localFont from "next/font/local";
// import "@/app/styles/layout.css"
import "./layout.css"
import { useRouter } from "next/navigation";
import { IoHomeOutline } from "react-icons/io5";
import { PiHandshakeDuotone } from "react-icons/pi";
import { SlEnvolopeLetter } from "react-icons/sl";
import { TbReportSearch } from "react-icons/tb";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  const navigateHome = ()=>{
    router.push("/home")
  }

  return (
    <html lang="en">
      <head>
        <title>
          R.R Governance
        </title>
        <link rel="icon" href="/logo.jpg" type="image/x-icon"></link>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div className="navbar-main">
        <div className="left-nav">
            <img src="/logo.jpg" alt="logo" className="app-logo"></img>
            <h1 className="app-name">R.R Governance</h1>
        </div>
        <div className="right-nav">
            <button className="nav-buttons" onClick={navigateHome}>
              <div className="emoji"><IoHomeOutline /> </div>
              Home</button>
            
            {/* <div className="dropdown">
                <button className="nav-buttons dropdown-button">
                    Forms
                    <span>   </span>
                    <span className="dropdown-icon">▼</span>
                </button>
                <div className="dropdown-content">
                    <a href="CheckIn">Check In Form</a>
                    <a href="NewEntry">New Entry Form</a>
                    <a href="CheckOut">Check Out Form</a>
                </div>
            </div> */}
            
            <div className="nav-buttons dropdown">
                <div className="emoji"><TbReportSearch /> </div>
                Reports
                <div className="dropdown-content">
                    <a href="#report1">Report 1</a>
                    <a href="#report2">Report 2</a>
                    <a href="#report3">Report 3</a>
                </div>
            </div>

            <div className="nav-buttons">
                <a href="/Help">
                <div><PiHandshakeDuotone /></div>
                Help & Support</a>
            </div>
            
            <div className="nav-buttons" >
                <a href="/AboutUs">
                <div><SlEnvolopeLetter/></div>
                About Us</a>
            </div>
        </div>
    </div>
        {children}
      </body>
    </html>
  );
}
